infer:
  modelname : "google/gemma-7b-it"
  adapter : "path adapter"
  output_dir : "./translated.csv"
  cache_dir : "./"
  hf_tokens : "hf_tokens"
  max_new_tokens : 512
  num_beams : 5
  early_stopping : True
  no_repeat_ngram_size : 1
  repetition_penalty : 1
  min_new_tokens : -1
  length_penalty : 2.0
  device : "cuda"
  top_k : 50
  top_p : 0.95
  temperature : 0.1
  use_cache : True
  do_sample : True


translate : 
  source_lang : "en"
  target_lang : "vi"
  file_path :
  text : "Hi, I'm doc translate bot"

